(defun pericuad()
(write "PERIMETRO DEL CUADRADO: ")
(princ "Dame el numero de la medida del lado: ")
(setq num1 (read))
(setq resultado (* num1 4))
(write resultado)
)

(defun perirec()
(princ "PERIMETRO DEL RECTANGULO  ")
(princ "Dame el numero de la medida del ancho: ")
(setq num1 (read))
(princ "Dame el numero de la medida del largo: ")
(setq num2 (read))
(setq resultado (+ (* num1 2) (* num2 2))
(write resultado)
))